SELECT * FROM V$VERSION;

SELECT * FROM DBA_SYS_PRIVS;

ALTER TABLE usuario ADD ID_PESSOA INTEGER;
ALTER TABLE conta ADD ID_CONTA INTEGER;
ALTER TABLE banco ADD ID_BANCO INTEGER;

ALTER TABLE CONTA DROP COLUMN ID_BANCO;

DELETE FROM USUARIO;       /* VAI EXCLUIR TODOS VALORES QUE FORAM PREENCHIDOS NA TABELA */
DELETE FROM BANCO;
DELETE FROM CONTA;

DROP TABLE BANCO;       /* VAI EXCLUIR A TABELA */
DROP TABLE PESSOA;
DROP TABLE CONTA;

    /* QUESTAO 3 */

SELECT NOME_PESSOA 
FROM pessoa
WHERE ID_PESSOA = 40;

ALTER TABLE pessoa ADD CONSTRAINT ID_PESSOA_PK PRIMARY KEY (ID_PESSOA);
ALTER TABLE banco ADD CONSTRAINT ID_BANCO_PK PRIMARY KEY (ID_BANCO);
ALTER TABLE conta ADD CONSTRAINT ID_CONTA_PK PRIMARY KEY (ID_CONTA);

/* Constraints – Constraints são objetos usados com a finalidade de estabelecer regras 
referentes à integridade e à consistência nas colunas das tabelas pertencentes a um sistema 
de banco de dados. Isso é importante porque para planejar e criar tabelas devemos garantir a 
integridade dos dados presentes nas colunas e identificar os valores válidos para tais dados.*/

CREATE TABLE pessoa (
    ID_PESSOA INTEGER NOT NULL,
    NOME_PESSOA VARCHAR2(30) NOT NULL,
    CPF VARCHAR2(14),
    CNPJ VARCHAR2(17),
    CONSTRAINT "ID_PESSOA_PK" PRIMARY KEY ("ID_PESSOA")
);

CREATE SEQUENCE SEQUENCE_PESSOA INCREMENT BY 1 
START WITH 1;
/* Uma SEQUENCE é um objeto no Oracle que é usado para gerar uma sequência de números. Pode ser 
útil quando você precisa criar um número exclusivo para atuar como uma chave primária. */

CREATE OR REPLACE TRIGGER TRIGGER_PESSOA
    BEFORE INSERT ON pessoa
    FOR EACH ROW
    BEGIN
      SELECT SEQUENCE_PESSOA.NEXTVAL INTO :NEW.ID_PESSOA FROM DUAL;
    END;
/* Um Trigger é um procedimento armazenado no banco de dados que é chamado automaticamente 
sempre que ocorre um evento especial no banco de dados. Por exemplo, um acionador pode ser 
chamado quando uma linha é inserida em uma tabela especificada ou quando determinadas colunas 
da tabela estão sendo atualizadas. */    

CREATE TABLE banco (
    ID_BANCO INTEGER NOT NULL,
    NOME VARCHAR2(30),
    CNPJ VARCHAR2(17),
    CONSTRAINT "ID_BANCO_PK" PRIMARY KEY ("ID_BANCO")
);

CREATE SEQUENCE SEQUENCE_BANCO INCREMENT BY 1 
START WITH 1;

CREATE OR REPLACE TRIGGER TRIGGER_BANCO
    BEFORE INSERT ON banco
    FOR EACH ROW
    BEGIN
      SELECT SEQUENCE_BANCO.NEXTVAL INTO :NEW.ID_BANCO FROM DUAL;
    END;

CREATE TABLE conta (
    ID_CONTA INTEGER NOT NULL,
    NOME_PESSOA VARCHAR2(30),
    TIPO_CONTA VARCHAR2(30),
    BANCO_NOME VARCHAR2(30),
    CONSTRAINT "ID_CONTA_PK" PRIMARY KEY ("ID_CONTA")
);

CREATE SEQUENCE SEQUENCE_CONTA INCREMENT BY 1 
START WITH 1;

CREATE OR REPLACE TRIGGER TRIGGER_CONTA
    BEFORE INSERT ON conta
    FOR EACH ROW
    BEGIN
      SELECT SEQUENCE_CONTA.NEXTVAL INTO :NEW.ID_CONTA FROM DUAL;
    END;

SELECT * FROM pessoa;

SELECT * FROM banco;

SELECT * FROM conta;

SELECT COUNT(1) FROM PESSOA;

SELECT NOME_PESSOA, CPF, CNPJ FROM pessoa
WHERE CPF LIKE '%3';

    /* QUESTAO 1 */

/* inserindo 12 valores na tabela pessoa */

INSERT INTO pessoa(NOME_PESSOA,CPF,CNPJ) VALUES('Rebeca Rayssa','05355526379',null);
INSERT INTO pessoa(NOME_PESSOA,CPF,CNPJ) VALUES('Maria Silva','08966527373',null);
INSERT INTO pessoa(NOME_PESSOA,CPF,CNPJ) VALUES('Gilbert',null,'11344599678245');
INSERT INTO pessoa(NOME_PESSOA,CPF) VALUES('Fiodor Dostoievski','38211893406');
INSERT INTO pessoa(NOME_PESSOA,CNPJ) VALUES('clarice lispector','44058698560337');
INSERT INTO pessoa(NOME_PESSOA,CNPJ) VALUES('Thomas Mann','44223000599855');
INSERT INTO pessoa(NOME_PESSOA,CNPJ) VALUES('Safira Peluda','00544783386341');
INSERT INTO pessoa(NOME_PESSOA,CPF) VALUES('Bilbo Bolseiro','77281999504');
INSERT INTO pessoa(NOME_PESSOA,CPF) VALUES('Gandalf Cinzento','00458921103');
INSERT INTO pessoa(NOME_PESSOA,CNPJ) VALUES('Sauron','77490000749502');
INSERT INTO pessoa(NOME_PESSOA,CPF) VALUES('Miles Davis',9877355166);
INSERT INTO pessoa(NOME_PESSOA,CNPJ) VALUES('Chet Baker',490596847356);

/* inserindo 13 valores na tabela banco */

INSERT INTO banco(NOME,CNPJ) VALUES('Nubank','18236120000158');
INSERT INTO banco(NOME,CNPJ) VALUES('Bradesco','60746948000112');
INSERT INTO bando(NOME,CNPJ) VALUES('Itau','60701190000104');
INSERT INTO banco(NOME,CNPJ) VALUES('Banco do Brasil','00000000000191');
INSERT INTO banco(NOME,CNPJ) VALUES('Santander','90400888000142');
INSERT INTO banco(NOME,CNPJ) VALUES('Inter','00416968000101');
INSERT INTO banco(NOME,CNPJ) VALUES('C6 Bank','61348538000186');
INSERT INTO banco(NOME,CNPJ) VALUES('Caixa','00360305000104');
INSERT INTO banco(NOME,CNPJ) VALUES('Inter','00416968000101');
INSERT INTO banco(NOME,CNPJ) VALUES('Caixa','00360305000104');
INSERT INTO banco(NOME,CNPJ) VALUES('Caixa','00360305000104');
INSERT INTO banco(NOME,CNPJ) VALUES('Caixa','00360305000104');
INSERT INTO banco(NOME,CNPJ) VALUES('Safra','581607890001');

/* inserindo valores na tabela conta */

INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');
INSERT INTO conta(NOME_PESSOA,TIPO_CONTA,BANCO_NOME) VALUES('','','');

        /* QUESTAO 2 */

SELECT * FROM BANCO;
SELECT * FROM CONTA;
SELECT * FROM PESSOA;

        /* QUESTAO 3 */
        
SELECT NOME_PESSOA FROM PESSOA;

SELECT ID_CONTA,TIPO_CONTA,BANCO_NOME FROM CONTA;

SELECT ID_BANCO FROM BANCO;

        /* QUESTAO 4 */
        
SELECT ID_PESSOA FROM PESSOA;
SELECT ID_CONTA FROM CONTA;
SELECT ID_BANCO FROM BANCO;

SELECT NOME_PESSOA FROM PESSOA
WHERE ID_PESSOA = 45;

SELECT NOME_PESSOA,TIPO_CONTA FROM CONTA
WHERE ID_CONTA = 8;

SELECT NOME,CNPJ FROM BANCO
WHERE ID_BANCO = 4;

        /* QUESTAO 5 */

UPDATE PESSOA
SET CPF = '29877355166'
WHERE ID_PESSOA = 52;

SELECT * FROM PESSOA;

UPDATE PESSOA
SET CNPJ = '49059684735604'
WHERE ID_PESSOA = 53;

UPDATE PESSOA
SET NOME_PESSOA = 'Galadriel'
WHERE ID_PESSOA = 54;

UPDATE PESSOA
SET CNPJ = '31239577892305'
WHERE ID_PESSOA = 54;

UPDATE BANCO
SET CNPJ = '58160789000177'
WHERE ID_BANCO = 12;

        /* QUESTAO 6 */
        
DELETE FROM PESSOA
WHERE ID_PESSOA = 55;

DELETE FROM PESSOA
WHERE ID_PESSOA = 56;

DELETE FROM BANCO
WHERE ID_BANCO = 9;

SELECT * FROM BANCO;

DELETE FROM BANCO
WHERE ID_BANCO = 10;

DELETE FROM BANCO
WHERE ID_BANCO = 11;

DELETE FROM BANCO
WHERE ID_BANCO = 8;



